import type { Metadata } from "next";
import { Suspense } from "react";

// These styles apply to every route in the application
import "../styles/global.css";
import { Loader } from "./components/Loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loader />}>{children}</Suspense>
      </body>
    </html>
  );
}
